INSERT INTO library.kinds (id, name)
  VALUES (1, '大型本');
  INSERT INTO library.kinds (id, name)
  VALUES (2, '絵本');
  INSERT INTO library.kinds (id, name)
  VALUES (3, '新書');
  INSERT INTO library.kinds (id, name)
  VALUES (4, '文庫');
  INSERT INTO library.kinds (id, name)
  VALUES (5, '雑誌');
  INSERT INTO library.kinds (id, name)
  VALUES (6, '図鑑');
  INSERT INTO library.kinds (id, name)
  VALUES (7, 'コミック');
