INSERT INTO library.shelves (id, name)
  VALUES (0, 'ëçãL');
  INSERT INTO library.shelves (id, name)
  VALUES (1, 'ìNäw');
  INSERT INTO library.shelves (id, name)
  VALUES (2, 'óéj');
  INSERT INTO library.shelves (id, name)
  VALUES (3, 'é–âÔâ»äw');
  INSERT INTO library.shelves (id, name)
  VALUES (4, 'é©ëRâ»äw');
  INSERT INTO library.shelves (id, name)
  VALUES (5, 'ãZèp');
  INSERT INTO library.shelves (id, name)
  VALUES (6, 'éYã∆');
  INSERT INTO library.shelves (id, name)
  VALUES (7, 'å|èp');
  INSERT INTO library.shelves (id, name)
  VALUES (8, 'åæåÍ');
  INSERT INTO library.shelves (id, name)
  VALUES (9, 'ï∂äw');